### ISSUE TITLE
Pushing to master

### ISSUE THREAD

**Issue by JoBa97** [ibogicevic/SCADinspect#279]
Please us pull requests instead of pushing directly to master. It is protected for a reason.

**Comment by ibogicevic** [comment]
I decided to change the process after sprint 3 as I thought that I am the only one left working on the project. There has been no contribution since the end of may, so I cannot assume that anyone else is willing to review pull requests and I won't create pull requests and add myself as a reviewer :-)
I'll immediately change the process back to the old scheme (changes only through feature branches via pull requests with at least one reviewer) if I knew that I am not alone on this project. Do you have the time and are you willing to continue working on the project (at least a bit)? If yes, I'd be very happy!
The project had no progress for a while but I would like to continue working on it during august so that we have a stable version until the beginning of september (only with the documentation feature, we don't have the manpower to fix the static code analysis part to a really useful state).
