### ISSUE TITLE
Create a GUI Prototype for a help modal 

### ISSUE THREAD

**Issue by jonasber** [ibogicevic/SCADinspect#48]
With the new GUI Prototype, a Help / Quick tour modal is added as a feature.  The Prototype can be found here: https://github.com/ibogicevic/SCADinspect/blob/master/spec/proto/sketch_proposal.ep
There is already a new section for the modal within the prototype.

The modal should guide the user if he opens the application for the first time and shows hints by overlaying. An example from a not related app: 
![hintoverlay](https://cloud.githubusercontent.com/assets/10549978/23800700/aa829bb4-05ad-11e7-8d31-f128d375b96f.png)

**Comment by ibogicevic** [comment]
That is a good idea. With this we have more space for the dialog and as it is modal we have no switching between windows which could be disturbing. The prototype is good, but please change two things:

1. We need the close-Button back (right next to the open-button) because although technically it is not needed, it is a common important usability guideline to provide the users the possibility to get the status his application was before his last action. Without the close-Button this wouldn't be possible.

2. I would like the text about SCADinspect to be moved to inside the help-dialog.
